=== wamidgette/TicketSystem/XML/tickets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="messages">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="content" type="xs:string">
                                                    </xs:element>
                                                    <xs:element name="timeStamp" type="xs:date">
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="sender" type="clientStaff" use="required"/>
                                                <xs:attribute name="userId" type="xs:positiveInteger" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="dateCreated" type="xs:date">
                            </xs:element>
                            <xs:element name="dateClosed" type="xs:date" minOccurs="0">
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="userId" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="ticketId" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="category" type="xs:token" use="required"/>
                        <xs:attribute name="status" type="openClosed" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="openClosed">
        <xs:restriction base="xs:token">
            <xs:enumeration value="open"/>
            <xs:enumeration value="closed"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="clientStaff">
        <xs:restriction base="xs:token">
            <xs:enumeration value="client"/>
            <xs:enumeration value="staff"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== wamidgette/TicketSystem/XML/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This will be a support ticket system for a company that sells a variety of tech products -->
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
    <ticket userId="0001" ticketId="0001" category="refunds" status="open">
        <messages>
            <message sender="client" userId="0001">
                <content>I would like to request a refund for my product</content>
                <timeStamp>2002-09-24-06:00</timeStamp><!-- this will be type dateTime -->
            </message>
            <message sender="staff" userId="0005">
                <content>Can you please provide the product name?</content>
                <timeStamp>2002-09-24-06:00</timeStamp>
            </message>
        </messages>
        <dateCreated>2002-09-24-06:00</dateCreated>
    </ticket>
    <ticket userId="0004" ticketId="0002" category="support" status="closed"><!-- all required -->
        <messages>
            <message sender="client" userId="0004">
                <content>I need information on how my product works</content>
                <timeStamp>2002-09-24-06:00</timeStamp>
            </message>
            <message sender="staff" userId="0010">
                <content>Please allow me to refer you to my collegue</content>
                <timeStamp>2002-09-24-06:00</timeStamp>
            </message>
            <message sender="staff" userId="0005"><!-- could have multiple support staff for one issue so userId must be required -->
                <content>The user manual is attached in the email sent to you on January 8, 2021. Can I help you with anything else?</content>
                <timeStamp>2002-09-24-06:00</timeStamp>
            </message>
            <message sender="client" userId="0004">
                <content>No, thank you, that will be all.</content>
                <timeStamp>2002-09-24-06:00</timeStamp>
            </message>
        </messages>
        <dateCreated>2002-09-24-06:00</dateCreated>
        <dateClosed>2002-09-24-06:00</dateClosed><!-- occurs 0 or 1 times -->
    </ticket>
</tickets>
