=== wamidgette/TicketSystem/XML/users.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" type="xs:string"/>
                                        <xs:element name="last" type = "xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" type="xs:string"/><!-- Dont konw - string for now  -->
                            <xs:element name="phone" type="xs:string"/><!-- Dont know - String for now -->
                            <xs:element name="login">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="userName" type="xs:string"/>
                                        <xs:element name="passWord" type="xs:string"/> <!-- Dont konw - string for now -->
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="clientStaff" use="required"/>
                        <xs:attribute name="userId" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="category" type="department"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="clientStaff">
        <xs:restriction base="xs:token">
            <xs:enumeration value="client"/>
            <xs:enumeration value="staff"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="department">
        <xs:restriction base="xs:token">
            <xs:enumeration value="customerService"/>
            <xs:enumeration value="techSupport"/>
            <xs:enumeration value="sales"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== wamidgette/TicketSystem/XML/users.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This will be a support ticket system for a company that sells a variety of tech products -->
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user type="client" userId="0001">
        <name>
            <first>Richard</first>
            <last>Thompson</last>
        </name>
        <email>rthompson@gmail.com</email>
        <phone>647-XXX-XXXX</phone>
        <login>
            <userName>rthompson</userName>
            <passWord>5f4dcc3b5aa765d61d8327deb882cf99</passWord>
        </login>
    </user>
    <user type="staff" userId="0002" category="customerService">
        <name>
            <first>Steven</first>
            <last>Johnson</last>
        </name>
        <email>sjohnson@support.com</email>
        <phone>416-XXX-XXXX</phone>
        <login>
            <userName>sjohnson</userName>
            <passWord>5f4dcc3b5aa765d61d8327deb882cf99</passWord>
        </login>
    </user>
    <user type="client" userId="0004">
        <name>
            <first>John</first>
            <last>MacDonald</last>
        </name>
        <email>jMacdonald@gmail.com</email>
        <phone>416-XXX-XXXX</phone>
        <login>
            <userName>jmacdonald</userName>
            <passWord>5f4dcc3b5aa765d61d8327deb882cf99</passWord>
        </login>
    </user>
    <user type="staff" userId="0005" category="customerService">
        <name>
            <first>Daniel</first>
            <last>Quintus</last>
        </name>
        <email>dQuintus@support.com</email>
        <phone>519-XXX-XXXX</phone>
        <login>
            <userName>dquintus</userName>
            <passWord>5f4dcc3b5aa765d61d8327deb882cf99</passWord>
        </login>
    </user>
    <user type="staff" userId="0010" category="customerService">
        <name>
            <first>Tom</first>
            <last>Fogerty</last>
        </name>
        <email>tFogert@support.com</email>
        <phone>519-XXX-XXXX</phone>
        <login>
            <userName>tFogerty</userName>
            <passWord>5f4dcc3b5aa765d61d8327deb882cf99</passWord>
        </login>
    </user>
</users>
